Fix Qt download

diff --git a/windows_dev_env/Dockerfile b/windows_dev_env/Dockerfile
--- a/windows_dev_env/Dockerfile
+++ b/windows_dev_env/Dockerfile
@@ -16,9 +16,8 @@ COPY qt-installer-noninteractive.qs C:\TEMP\
 # Download and install Build Tools for Visual Studio 2017 for native desktop workload.
 RUN  powershell -Command "Invoke-WebRequest 'https://aka.ms/vs/16/release/vs_buildtools.exe' -OutFile 'C:\TEMP\vs_buildtools.exe'" `
   && powershell -Command "Invoke-WebRequest 'http://releases.llvm.org/8.0.0/LLVM-8.0.0-win64.exe' -OutFile 'C:\TEMP\llvm.exe'" `
-  && powershell -Command "Invoke-WebRequest 'https://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe' -OutFile 'C:\Temp\qt.exe'" `
-  && C:\Temp\qt.exe --script C:\Temp\qt-installer-noninteractive.qs --platform=minimal --logging-rules "ifw.*=true" --verbose `
-  && RD /S /Q C:\Users\%USERNAME%\AppData\Local\Temp C:\Qt\Docs C:\Qt\Examples C:\Qt\Tools `
+  && powershell -Command "Invoke-WebRequest 'http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe' -OutFile 'C:\Temp\qt.exe'" `
+  && (C:\Temp\qt.exe --script C:\Temp\qt-installer-noninteractive.qs --platform=minimal --logging-rules "ifw.*=true" --verbose || echo "Qt installed failed") `
   && C:\TEMP\vs_buildtools.exe --quiet --wait --norestart --nocache `
     --channelUri C:\TEMP\VisualStudio.chman `
     --installChannelUri C:\TEMP\VisualStudio.chman `
@@ -30,9 +29,9 @@ RUN  powershell -Command "Invoke-WebRequest 'https://aka.ms/vs/16/release/vs_bui
     --add Microsoft.Component.VC.Runtime.UCRTSDK `
     --add Microsoft.Component.MSBuild `
     --installPath C:\BuildTools `
-  && RD /S /Q "C:\ProgramData\Package Cache" `
   && powershell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1'))" `
-  && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
+  && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin `
+  && (RD /S /Q "C:\Users\%USERNAME%\AppData\Local\Temp" C:\Qt\Docs C:\Qt\Examples C:\Qt\Tools "C:\ProgramData\Package Cache" 2>nul || echo "Unable to remove file!")
 
 RUN powershell choco feature disable --name showDownloadProgress && choco install git.install -y --params "'/GitAndUnixToolsOnPath /NoAutoCrlf'" `
   && choco install nodejs ninja 7zip nsis -y --ignoredetectedreboot -ignore-package-exit-codes `
@@ -63,8 +62,8 @@ RUN powershell choco feature disable --name showDownloadProgress && choco instal
     boost-smart-ptr:x64-windows-static boost-smart-ptr:x86-windows-static `
     boost-optional:x64-windows-static boost-optional:x86-windows-static `
     openssl:x64-windows openssl:x86-windows `
-  && 7z x C:\Temp\llvm.exe -oC:\LLVM && setx PATH "%path%;C:\\llvm\\bin" && setx LLD_LINK "C:\\llvm\\bin\\lld-link.exe"`
-  && RD /S /Q C:\vcpkg\downloads C:\vcpkg\buildtrees C:\vcpkg\packages C:\Temp`
+  && 7z x C:\Temp\llvm.exe -oC:\LLVM && setx PATH "%path%;C:\\llvm\\bin" && setx LLD_LINK "C:\\llvm\\bin\\lld-link.exe" `
+  && (RD /S /Q C:\vcpkg\downloads C:\vcpkg\buildtrees C:\vcpkg\packages C:\Temp || echo "Unable to remove filees!") `
 
 # Use developer command prompt and start PowerShell if no other command specified.
 #ENTRYPOINT C:\BuildTools\Common7\Tools\VsDevCmd.bat &&
